### PR TITLE
Allow other extensions to register shared models

### PR DESCRIPTION
**Pull request by hbcarlos**
Fixes JupyterCAD and Glue-lab

cc @trungleduc @martinRenou

### CODE REVIEW

**Comment by trungleduc** [comment]
Why do we accept only the `string` file format here? https://github.com/jupyterlab/jupyter_collaboration/blob/2432fe032cce3414836ef035fe975acb1fcd8655/packages/docprovider/src/ydrive.ts#L201-L203

**Comment by hbcarlos** [comment]
Because the [file format can be null](https://github.com/jupyterlab/jupyterlab/blob/ed0e0eb9251546cce0acef580c7b6349ee9bbad8/packages/services/src/contents/index.ts#L134) and we need it to create the room id in the document provider. See https://github.com/jupyterlab/jupyter_collaboration/blob/2432fe032cce3414836ef035fe975acb1fcd8655/packages/docprovider/src/ydrive.ts#L124

**Comment by trungleduc** [comment]
`JupyterCad` defines the `FCStd` file format as `base64`, it will work here?

**Comment by hbcarlos** [comment]
> JupyterCad defines the FCStd file format as base64, it will work here?

Yes. We are checking the attribute type (`typeof options.format`), not the attribute itself.

**Review by trungleduc — APPROVED** [review]

**Review by davidbrochart — APPROVED** [review]

**Pull request merged**
